### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by gkuhlmann14** [appleboy/gorush#199]
Hi, 

Getting the following error when trying to push to production via the server endpoints:
`net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
Server is returning:
```
{
  "success": "ok"
}
```
was wondering if anyone's seeing this, seems to be working for me with my dev push certificate

**Comment by gkuhlmann14** [comment]
```
core:
  port: "140xx"
  max_notification: 100
  worker_num: 1
  queue_num: 8192
  mode: release
  ssl: false
  cert_path: cert.pem
  key_path: key.pem
  http_proxy: ""
  pid:
    enabled: true
    path: gorush.pid
    override: true
api:
  push_uri: /api/push
  stat_go_uri: /api/stat
  stat_app_uri: /api/stat/app
  config_uri: /api/config
  sys_stat_uri: /sys/stats
  metric_uri: /metrics
android:
  enabled: false
  apikey: YOUR_API_KEY
  max_retry: 0
ios:
  enabled: true
  key_path: mycert.p12
  password: mypassword
  production: true
  max_retry: 1
log:
  format: string
  access_log: stdout
  access_level: debug
  error_log: stderr
  error_level: error
  hide_token: true
stat:
  engine: memory
  redis:
    addr: localhost:6379
    password: ""
    db: 0
  boltdb:
    path: bolt.db
    bucket: gorush
  buntdb:
    path: bunt.db
  leveldb:
    path: level.db
```
