### ISSUE TITLE
Persistence of pending notifications?

### ISSUE THREAD

**Issue by gardenia** [appleboy/gorush#330]
Hi,

Am I correct in understanding that there is no persistence of the pending notifications  e.g. if gorush were to be restarted any pending push notifications would be lost?

If so do you have any plans to support queueing in something like rabbitmq or redis (or even a relational DB)?

In my opinion this would be a good feature for robustness but I'd be interested to hear your opinion.

Thanks.

**Comment by xnathanh** [comment]
I personally think that no necessary, the queue should be in the logic of the program needs,
gorush should be a pure push service,Unless the author wants gorush to be a push platform

**Comment by renatocron** [comment]
Is that not what "Support store app stat to memory, Redis, BoltDB, BuntDB or LevelDB" means?

If not, what is being saved on that stores so?

**Comment by appleboy** [comment]
We need the database to store the notification status or support third-party queuing system service.

**Comment by phpfs** [comment]
+1 on this - would be a great feature :)

**Comment by appleboy** [comment]
We can send the notification message to a specific URL. Please see the following setting in YAML:

```yaml
core:
  feedback_hook_url: "" # set a hook url if you need get error message asynchronously from fail push notification in API response.
  feedback_timeout: 10 # default is 10 second
```
