### ISSUE TITLE
Always response count is 0 in latest verison

### ISSUE THREAD

**Issue by TianDaGe** [appleboy/gorush#345]
Hi, @appleboy 
I am trying to use latest version. but it is not working fine as like older version.

```
{
  "notifications": [
    {
      "tokens": ["11671c2e7da3***********e37ba5d3e6a617be"],
      "platform": 1,
      "message": "Hello World",
      "topic":"com.xxx.xxxx"
    }
  ]
}
```
Response is always like this.
```
{
    "counts": 0,
    "logs": [],
    "success": "ok"
}
```

I set already "sync" by "true" in config.yml.
I checked latest version(Mac&Windows version) with latest config.yml style. but as you can see it is not working correctly, 
My test older version(1.7.4) is working fine.
What is the issue?

**Comment by appleboy** [comment]
I will take it.

**Comment by TianDaGe** [comment]
is there any update?

**Comment by appleboy** [comment]
It is working for me with the latest version.

![snip20180322_2](https://user-images.githubusercontent.com/21979/37762676-01c4ffc0-2df8-11e8-9fda-fcc0776e2210.png)
![snip20180322_4](https://user-images.githubusercontent.com/21979/37762677-01eeecea-2df8-11e8-8655-08599dbf4ff3.png)

iOS config is not enabled by default. Please update your config.

**Comment by TianDaGe** [comment]
can you share your current config?

**Comment by appleboy** [comment]
```yml
core:
  enabled: true
  port: "8088"
  worker_num: 0
  queue_num: 0
  max_notification: 100
  mode: "debug"
  sync: true
  ssl: false
  cert_path: "certificate/localhost.cert"
  key_path: "certificate/localhost.key"
  cert_string_base64: ""
  key_string_base64: ""
  http_proxy: ""
  pid:
    enabled: true
    path: "custom/gorush.pid"
    override: true

grpc:
  enabled: true
  port: 9000

api:
  push_uri: "/api/push"
  stat_go_uri: "/api/stat/go"
  stat_app_uri: "/api/stat/app"
  config_uri: "/api/config"
  sys_stat_uri: "/sys/stats"
  metric_uri: "/metrics"
  health_uri: "/healthz"

android:
  enabled: true
  apikey: "xxxxxxx"
  max_retry: 0

ios:
  enabled: false
  key_path: "_test/gs.pem"
  key_string_base64: ""
  password: "" # certificate password, default as empty string.
  production: true
  max_retry: 2

log:
  format: "string"
  access_log: "stdout"
  access_level: "debug"
  error_log: "stderr"
  error_level: "error"
  hide_token: true

stat:
  engine: "memory"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
  boltdb:
    path: "bolt.db"
    bucket: "gorush"
  buntdb:
    path: "bunt.db"
  leveldb:
    path: "level.db"
```

json body:

```json
{
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 1,
      "message": "Hello World iOS!"
    },
    {
      "tokens": ["token_a", "token_b"],
      "platform": 2,
      "message": "Hello World Android!"
    }
  ]
}

```
