### ISSUE TITLE
support sending to multiple different certs

### ISSUE THREAD

**Issue by gardenia** [appleboy/gorush#365]
Hi,

At the moment it appears I can configure exactly one Android API key and one IOS push certificate.

I would like the capability to somehow disptach to different Android API keys and IOS push certificates, perhaps based on an app bundle id. I realize I could run N instances of gorush to accomplish that but it seems more ideal to be be able to do it all from the same process.

What do you think?

e.g. 

```
android:
  com.foo.bar:
    enabled: true
    apikey: "YOUR_API_KEY1"
    max_retry: 0 # resend fail notification, default value zero is disabled
  com.blah.blah:
    enabled: true
    apikey: "YOUR_API_KEY2"
    max_retry: 0 # resend fail notification, default value zero is disabled
```
