### ISSUE TITLE
Env Variables list

### ISSUE THREAD

**Issue by TarekAS** [appleboy/gorush#398]
Can't find a list of environment variables we could use. For example, where is GORUSH_STAT_ENGINE defined?
Could use better docs. We need this to pass env variables to K8s pods.

**Comment by appleboy** [comment]
See the yaml file:

```yml
core:
  enabled: true # enabale httpd server
  address: "" # ip address to bind (default: any)
  port: "8088" # ignore this port number if auto_tls is enabled (listen 443).
  worker_num: 0 # default worker number is runtime.NumCPU()
  queue_num: 0 # default queue number is 8192
  max_notification: 100
  sync: false # set true if you need get error message from fail push notification in API response.
  mode: "release"
```

`GORUSH_` as a prefix key. `GORUSH_CORE_ADDRESS` is p address to bind (default: any). I will update in README.
