### ISSUE TITLE
Sync doesn't seem to be working

### ISSUE THREAD

**Issue by eric-cancil** [appleboy/gorush#419]
Hello, and thanks for writing this server.

I have it configure in docker compose as follows.

```
  gorush:
    image: appleboy/gorush
    ports:
      - "8088:8088"
   environment:
      - GORUSH_CORE_SYNC=true
```

When I make a request I expect to get an error back to my http request (since I haven't configured any other bits, however I see the below, and always get 200s back.

```
gorush_1            | [GIN] 2019/07/18 - 23:48:03 | 200 |  162.702369ms |      172.18.0.1 | POST     /api/push
gorush_1            | time="2019/07/18 - 23:48:03" level=error msg="FCM server send message error: 401 error: 401 Unauthorized"
```

Would really appreciate any feedback.
