### ISSUE TITLE
Gorush ignores custom config

### ISSUE THREAD

**Issue by setevoy2** [appleboy/gorush#468]
I'm trying to run Gorush in a Kubernetes pod.
I have a certificate mounted to the pod, and a config file.
The problem is that after it's running - GET /api/config returns default values - not from the /config.yml.

I also found, that Gorush **totally ignores** a config file if it has any errors - but Gorush WILL NOT raise any exceptions or any message to its logs - just starts using its default values in absolute silence.

My config.yml:

```
core:
  enabled: true
  mode: "release"
  port: "8088"
  max_notification: 1000
  sync: true

api:
  push_uri: "/api/push"
  stat_go_uri: "/api/stat/go"
  stat_app_uri: "/api/stat/app"
  config_uri: "/api/config"
  sys_stat_uri: "/sys/stats"
  metric_uri: "/metrics"
  health_uri: "/healthz"

android:
  enabled: false
  apikey: "YOUR_API_KEY"

ios:
  enabled: true
  key_path: "/data/ssl/apns-crt.p12"
  password: "password"
  production: true

log:
  format: "string" # string or json
  access_log: "stdout" # stdout: output to console, or define log path like "log/access_log"
  access_level: "debug"
  error_log: "stderr" # stderr: output to console, or define log path like "log/error_log"
  error_level: "debug"
  hide_token: false

stat:
  engine: "redis" # support memory, redis, boltdb, buntdb or leveldb

```

The cert file `/data/ssl/apns-crt.p12` is present in the pod.

What can be wrong here?

I'm able to run gorush with the same file as above using local Docker - after start it says "_Using config file: /config.yml_", but it won't work from a Kuber's pod.

**Comment by appleboy** [comment]
You should use the config map in k8s.

See [configmap.yaml](https://github.com/appleboy/gorush/blob/master/k8s/gorush-configmap.yaml) and [deployment.yml](https://github.com/appleboy/gorush/blob/dbc57cd828005b441814d6b72808750a04577a15/k8s/gorush-deployment.yaml#L26-L36)

**Comment by setevoy2** [comment]
I'm using them, yes.
I have a dedicate configMap, and it's mounted to the pod:

```
        volumeMounts:
        - name: ios-push-secret-vol
          mountPath: /data/ssl/apns-crt.p12
          subPath: apns-crt.p12
          readOnly: true
        - name: gorush-config-file-vol
          mountPath: /config.yml
          readOnly: true
          subPath: config.yml
```

It then is present in the pod.

Cert:

```
$ kubectl -n gorush exec -ti gorush-6486ccd8cc-z7z2b -c gorush ls  /data/ssl
apns-crt.p12
```
Config:

```
$ kubectl -n gorush exec -ti gorush-6486ccd8cc-z7z2b -c gorush cat /config.yml
core:
  enabled: true
  mode: "release"
  port: "8088"
  max_notification: 1000
  sync: true

api:
  push_uri: "/api/push"
  stat_go_uri: "/api/stat/go"
  stat_app_uri: "/api/stat/app"
  config_uri: "/api/config"
  sys_stat_uri: "/sys/stats"
  metric_uri: "/metrics"
  health_uri: "/healthz"

android:
  enabled: false
  apikey: "YOUR_API_KEY"

ios:
  enabled: true
  key_path: "/data/ssl/apns-crt.p12"
  password: "password"
  production: true

log:
  format: "string" # string or json
  access_log: "stdout" # stdout: output to console, or define log path like "log/access_log"
  access_level: "debug"
  error_log: "stderr" # stderr: output to console, or define log path like "log/error_log"
  error_level: "debug"
  hide_token: false

stat:
  engine: "redis" # support memory, redis, boltdb, buntdb or leveldb
```

Also, wondering why Gorush says absolutely nothing if a config file has any misprints/errors?
Just a "blablabla" at the end of the config, restart the Gorush - it will just omit using /config.yml and will start using default values.

So, something may be wrong with my config (what? it works locally via Docker), but Gorush says nothing about what exactly.

**Comment by setevoy2** [comment]
Aha, okay.
I made it working using default configMap `gorush-config` instead of creating an additional one with the full config.yml content and mount it as a file to the /config.yml- just added mine data in there:

```
data:
  # stat
  stat.engine: redis
  stat.redis.host: redis:6379
  ios.enabled: "true"
  ios.key_path: /data/ssl/apns-crt.p12
  ios.password: password
  ios.production: "true"
```

And then using it in the deployment, as you did it for the Redis:

```
        - name: GORUSH_STAT_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: stat.redis.host
        - name: GORUSH_IOS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: ios.enabled
```

**Comment by appleboy** [comment]
I will close the issue, please feel free to reopen if you have another problem.

**Comment by setevoy2** [comment]
@appleboy Well, actually yes - got another issue related to this case :-)

So. now I'm using envs passed to the pod:

```
        - name: GORUSH_IOS_KEY_PATH
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: ios.key_path
        - name: GORUSH_IOS_PRODUCTION
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: ios.production
        - name: GORUSH_IOS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: gorush-config
              key: ios.password
```

And then in the default configMap:

```
data:
  # stat
  stat.engine: redis
  stat.redis.host: redis:6379
  ios.enabled: "true"
  ios.key_path: /data/ssl/apns-crt.p12
  ios.password: password
  ios.production: "true"
```

The problem here is the Password as it's hardcoded to the configMap.

But if move it to the Secret object and then use for the `GORUSH_IOS_PASSWORD` variable:

```
        - name: GORUSH_IOS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ios-push-secret
              key: ios-push-p12-pass
```

It will not work:

> $ kubectl -n gorush logs -f Deployments/gorush gorush | grep -v 'ELB-\|healt'
> Found 2 pods, using pod/gorush-754dcdd469-kb5bv
> {"level":"info","msg":"Init App Status Engine as redis","time":"2020-02-11T10:14:47Z"}
> {"level":"info","msg":"worker number is 2, queue number is 8192","time":"2020-02-11T10:14:47Z"}
> {"level":"error","msg":"Cert Error:pkcs12: decryption password incorrect","time":"2020-02-11T10:14:47Z"}
> {"level":"fatal","msg":"pkcs12: decryption password incorrect","time":"2020-02-11T10:14:47Z"}

Although `GORUSH_IOS_PASSWORD` is present inside of a pod and has a correct value.

P.S. Also - we weren't able to run using a PEM-encoded key, didn't made a dedicated issue for this.
