### ISSUE TITLE
Memory and Goroutine grow constantly

### ISSUE THREAD

**Issue by dukepan2005** [appleboy/gorush#518]
I deployed gorush by the "supervisor" tool.
But seems the memory grows waywardly.

![image](https://user-images.githubusercontent.com/13434393/84001623-97cb6080-a999-11ea-9af2-3ffa6660c051.png)

I checked /stat/go, the NumGoroutine is strange:

![image](https://user-images.githubusercontent.com/13434393/84001860-132d1200-a99a-11ea-8bcf-0461ff190165.png)

In fact, the goroutine_num always increases like memory.

my gorush version as following:

> GoRush v1.12.0, Compiler: gc go1.14, Copyright (C) 2019 Bo-Yi Wu, Inc

following is my config:

```
log:
  format: "string" # string or json
  access_log: "stdout" # stdout: output to console, or define log path like "log/access_log"
  access_level: "info"
  error_log: "stderr" # stderr: output to console, or define log path like "log/error_log"
  error_level: "error"
  hide_token: true

stat:
  **engine: "memory"** # support memory, redis, boltdb, buntdb or leveldb
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
  boltdb:
    path: "bolt.db"
    bucket: "gorush"
  buntdb:
    path: "bunt.db"
  leveldb:
    path: "level.db"
  badgerdb:
    path: "badger.db"
```
