### ISSUE TITLE
config

### ISSUE THREAD

**Issue by yxb-git** [appleboy/gorush#527]
Can't load log module, error: Set access log level error: not a valid logrus Level: ""

**Comment by appleboy** [comment]
Please provide more detailed information like Gorush config or your steps.

**Comment by appleboy** [comment]
Please set the default value in Log section.

```
log:
  format: "string"
  access_log: "stdout"
  access_level: "debug"
  error_log: "stderr"
  error_level: "error"
  hide_token: true
```
