### ISSUE TITLE
Enviroment variables in Config.yml ?

### ISSUE THREAD

**Issue by Mathgobbo** [appleboy/gorush#563]
I'd like to know if there is any way to use enviroment variables in the config.yml. 
I'm using docker-compose with a custom config.yml.

Is there any way to add the env variables in the docker-compose service and the config.yml can read them?

**Comment by appleboy** [comment]
Yes, see the YAML example:

```yaml
core:
  enabled: true # enable httpd server
  address: "" # ip address to bind (default: any)
  shutdown_timeout: 30 # default is 30 second
  port: "8088" # ignore this port number if auto_tls is enabled (listen 443).
  worker_num: 0 # default worker number is runtime.NumCPU()
  queue_num: 0 # default queue number is 8192
  max_notification: 100
```

Set `GORUSH_MAX_NOTIFICATION` to change the `max_notification` value.
