### ISSUE TITLE
Config android apikey vs. payload api_key

### ISSUE THREAD

**Issue by nevotheless** [appleboy/gorush#741]
Hello! I'm fiddling around with gorush atm and don't seem to understand what the 

```yaml
android:
  enabled: true
  apikey: "YOUR_API_KEY"
  max_retry: 0 # resend fail notification, default value zero is disabled
```

portion of the config file is for? I assumed i can put my firebase serverkey in there and send requests like

**/api/push**
```json
{
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 2,
      "message": "This notification will go to iOS and Android platform via Firebase!"
    }
  ]
}
```

instead i have to send requests like

```json
{
  "notifications": [
    {
      "api_key": "somefirebaseserverkey",
      "tokens": ["token_a", "token_b"],
      "platform": 2,
      "message": "This notification will go to iOS and Android platform via Firebase!"
    }
  ]
}
```

to prevent running into 401 authentication issues.

But when i do this, i question what gorush is good for if i have to provide the api_key myself in the payload. 
Seems like i'm missing some crucial info here.
