### ISSUE TITLE
http server not running.

### ISSUE THREAD

**Issue by fengyuxx** [appleboy/gorush#749]
Run a gorush in eks with version 1.16.3.

The log says that port 80 has been started. 
However, accessing /healthz prompts that the connection is refused. 
Enter the container and execute the "netstat -an" command. 
It is found that only port 9000 of grpc is LISTEN, and port 80 of http is not exists. 
But in version 1.11.2, you can see that both 80 and 9000 are LISTEN.

#log:
```
$ kubectl logs -f gorush-server-756cb5d797-m22g6
Using config file: /etc/gorush/config.yaml
{"level":"info","msg":"Init App Status Engine as memory","time":"2023-09-25T06:51:32Z"}
{"level":"info","msg":"HTTPD server is running on 80 port.","time":"2023-09-25T06:51:32Z"}
{"level":"info","msg":"gRPC server is running on 9000 port.","time":"2023-09-25T06:51:32Z"}
```

#config file:
```
core:
  enabled: true # enabale httpd server
  address: "" # ip address to bind (default: any)
  shutdown_timeout: 30 # default is 30 second
  port: "80" # ignore this port number if auto_tls is enabled (listen 443).
  worker_num: 0 # default worker number is runtime.NumCPU()
  queue_num: 65535 # default queue number is 8192
  max_notification: 100
  sync: false # set true if you need get error message from fail push notification in API response.
  mode: "release"
  ssl: false
  cert_path: "cert.pem"
  key_path: "key.pem"
  cert_base64: ""
  key_base64: ""
  http_proxy: "" # only working for FCM server
  pid:
    enabled: true
    path: "gorush.pid"
    override: true
  auto_tls:
    enabled: false # Automatically install TLS certificates from Let's Encrypt.
    folder: ".cache" # folder for storing TLS certificates
    host: "" # which domains the Let's Encrypt will attempt
grpc:
  enabled: true # enabale gRPC server
  port: 9000
api:
  push_uri: "/api/push"
  stat_go_uri: "/api/stat/go"
  stat_app_uri: "/api/stat/app"
  config_uri: "/api/config"
  sys_stat_uri: "/sys/stats"
  metric_uri: "/metrics"
  health_uri: "/healthz"
android:
  enabled: true
  apikey: "YOUR_API_KEY"
  max_retry: 0 # resend fail notification, default value zero is disabled
queue:
  engine: "local"
ios:
  enabled: true
  key_path: "/etc/gorush/certs/cert.p12"
  key_base64: "" # load iOS key from base64 input
  key_type: "p12" # could be pem, p12 or p8 type
  password: "" # certificate password, default as empty string.
  production: false
  max_retry: 0 # resend fail notification, default value zero is disabled
  key_id: "" # KeyID from developer account (Certificates, Identifiers & Profiles -> Keys)
  team_id: "" # TeamID from developer account (View Account -> Membership)
log:
  format: "string" # string or json
  access_log: "stdout" # stdout: output to console, or define log path like "log/access_log"
  access_level: "debug"
  error_log: "stderr" # stderr: output to console, or define log path like "log/error_log"
  error_level: "error"
  hide_token: true
stat:
  engine: "memory" # support memory, redis, boltdb, buntdb or leveldb
```

#pod describe
```
Name:         gorush-server-756cb5d797-m22g6
Namespace:    default
Priority:     0
Node:         ip-10-0-38-86.ap-east-1.compute.internal/10.0.38.86
Start Time:   Mon, 25 Sep 2023 14:51:29 +0800
Labels:       app=gorush-server
              pod-template-hash=756cb5d797
              release=gorush-server
Annotations:  checksum/config: 7f209d06009da13cab347320d52d78304ef883e3f3854a44b86530b0aca2cade
Status:       Running
IP:           10.0.34.27
IPs:
  IP:           10.0.34.27
Controlled By:  ReplicaSet/gorush-server-756cb5d797
Containers:
  gorush-server:
    Container ID:  containerd://1e7a657992beeeacfa2f532cf7b1e761c390f7ff6b9edc92e146351ad77fe2bc
    Image:         appleboy/gorush:1.16.3
    Image ID:      docker.io/appleboy/gorush@sha256:7079ce8b61a8bc8a5f0bd21161412d5b822e8ebe8bfffe8a1e4e6f25c01c38b0
    Ports:         80/TCP, 9000/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --apikey
      $(ANDROID_APIKEY)
    State:          Running
      Started:      Mon, 25 Sep 2023 14:51:31 +0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:http/healthz delay=3s timeout=1s period=300s #success=1 #failure=3
    Environment:
      ANDROID_APIKEY:  <set to the key 'apikey' in secret 'push-secret'>  Optional: false
    Mounts:
      /etc/gorush from config (rw)
      /etc/gorush/certs from ios-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-z92g6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      gorush-server-configmap
    Optional:  false
  ios-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  push-secret
    Optional:    false
  kube-api-access-z92g6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  52s   default-scheduler  Successfully assigned default/gorush-server-756cb5d797-m22g6 to ip-10-0-38-86.ap-east-1.compute.internal
  Normal  Pulling    51s   kubelet            Pulling image "appleboy/gorush:1.16.3"
  Normal  Pulled     50s   kubelet            Successfully pulled image "appleboy/gorush:1.16.3" in 1.598427182s (1.598452744s including waiting)
  Normal  Created    50s   kubelet            Created container gorush-server
  Normal  Started    49s   kubelet            Started container gorush-server
```
