### ISSUE TITLE
Sending to android via GRPC not work after update 

### ISSUE THREAD

**Issue by vanohaker** [appleboy/gorush#789]
**App version: 1.18.3, 1.18.4**

**Deploy  environment: kubernetes**

**Config:**
```yaml
  android:
    enabled: true
    key_path: "/vault/secrets/fcmkey.json"
    max_retry: 0
  api:
    config_uri: /api/config
    health_uri: /healthz
    metric_uri: /metrics
    push_uri: /api/push
    stat_app_uri: /api/stat/app
    stat_go_uri: /api/stat/go
    sys_stat_uri: /sys/stats
  core:
    enabled: true
    max_notification: 100
    mode: release
    pid:
      enabled: false
      override: true
      path: gorush.pid
    port: "8088"
    queue_num: 0
    shutdown_timeout: 30
    worker_num: 0
  grpc:
    enabled: true
    port: 9000
  huawei:
    enabled: true
    appsecret: "*****159e1a78c**********"
    appid: "*************"
    max_retry: 0
  ios:
    enabled: false
  log:
    access_level: debug
    access_log: stdout
    error_level: error
    error_log: debug
    format: string
    hide_messages: true
    hide_token: true
  queue:
    engine: redis
    redis:
      addr: gorush-dev-redis-master:6379
      group: gorush
      consumer: gorush
      stream_name: gorush
  stat:
    engine: memory
```

**Postman request:**
```json
{
    "platform": 2,
    "tokens": ["********_GdIgJYxXOcBd:APA91bFfWcR_RGaHavl1fdgeLJcvFPsPLEbH8jdgoJERpiKKO6yEttX-RNf2TLyo99CqvWZUK43jyCbmqfrbZOBS*********"],
    "data": {
        "fields": {
            "title": {
                "string_value": "123"
            }
        }
    }
}
```

Postman responde:
```json
{
    "success": true,
    "counts": 1
}
```

**Log:**
```json
{"level":"debug","msg":"Start push notification for Android","time":"2024-06-21T10:39:40Z"}
{"level":"debug","msg":"Android Success count: 0, Failure count: 1","time":"2024-06-21T10:39:40Z"}
```

If i rollback to 1.18.2 it work fine.
