### ISSUE TITLE
Feedback url is not receiving

### ISSUE THREAD

**Issue by sanjaylakum7** [appleboy/gorush#813]
I am currently experiencing an issue with Gorush feedback URL configuration. Despite successfully receiving push notifications and responses in the console log, no response is being sent to the specified feedback_hook_url.

Core Configuration:

```
core:
  feedback_hook_url: "https://example.com/notification-response/feedback-url/"
  feedback_timeout: 10
  feedback_header:
    - x-gorush-token: 12345
  mode: "release"
  ssl: false
  cert_path: "cert.pem"
  key_path: "key.pem"
  cert_base64: ""
  key_base64: ""
  http_proxy: ""
  pid:
    enabled: false
    path: "gorush.pid"
    override: true
  auto_tls:
    enabled: false
    folder: ".cache"
    host: ""

```
```

# Request body
curl --location 'http://localhost:8088/api/push' \
--data '{
    "notifications": [
        {
            "tokens": [
                "Token1"
            ],
            "platform": 2,
            "message": "This is my msg"
        }
    ]
}'

```

# Problem:
**Expected behavior:** The response should be sent to the configured feedback_hook_url.
**Actual behavior:** No response is being sent to the feedback_hook_url. However, the response is being logged in the console.

# Additional Information:
- The core is running in release mode.
- SSL is disabled.
- Feedback headers are properly configured with a token.
